---
title: "Sarah M. Weinstein"
---

smweinst [at] pennmedicine [dot] upenn [dot] edu

#### __Education__

PhD, Biostatistics (expected May 2023)

- University of Pennsylvania, Perelman School of Medicine (Philadelphia, PA)

- Advisors: Russell (Taki) Shinohara, PhD and Kristin Linn, PhD

- National Science Foundation Graduate Research Fellow (awarded 2018)

MS, Biostatistics (May 2020)

- University of Pennsylvania, Perelman School of Medicine (Philadelphia, PA)

- Advisor: Alisa Stephens-Shields, PhD

- Thesis: Simulation-based Design of Pragmatic Trials in Psoriatic Arthritis Using Propensity Scores

BA, Statistics and Psychology (May 2016)

- Columbia University, Columbia College (New York, NY)

- Honors: Cum Laude, Dean's List every semester

#### __Teaching__

Teaching Assistant for Introduction to Linear Models (Spring 2020)

- Department of Biostatistics, Epidemiology, and Informatics, University of Pennsylvania (Spring 2020)

Peer tutor (Fall 2015-Spring 2016)

- Department of Statistics, Columbia University

#### __Previous research experience__

Research Data Analyst (June 2016-July 2018) 

- Hospital for Special Surgery, Department of Anesthesiology, Critical Care, and Pain Management (New York, NY)

Undergraduate Research Assistant

- Perinatal Pathways Lab, Columbia University Medical Center (PI: Catherine Monk, PhD) (Summer 2013-Spring 2016)

- Champagne Lab, Department of Psychology, Columbia University (PI: Frances Champagne, PhD) (Fall 2014-Spring 2016)

- Department of Statistics, Columbia University (advised by Drs. Andrew Gelman and Jon Zelner) (Summer 2015)

#### __Publications__

Poeran J, Cozowicz C, Zubizarreta N, __Weinstein SM__, Deiner SG, Leipzig RM, Friedman JI, Liu J, Mazumdar M, Memtsoudis SG. Modifiable factors associated with postoperative delirium after hip fracture repair: An age-stratified retrospective cohort study. European Journal of Anaesthesiology| EJA. 2020 Aug 1;37(8):649-58.

Memtsoudis S, Cozowicz C, Zubizarreta N, __Weinstein SM__, Liu J, Kim DH, Poultsides L, Berger MM, Mazumdar M, Poeran J. Risk factors for postoperative delirium in patients undergoing lower extremity joint arthroplasty: a retrospective population-based cohort study. Regional Anesthesia & Pain Medicine. 2019 Oct 1;44(10):934-43.

Pichler L, __Weinstein SM__, Cozowicz C, Poeran J, Liu J, Poultsides LA, Saleh JN, Memtsoudis SG. Perioperative impact of sleep apnea in a high-volume specialty practice with a strong focus on regional anesthesia: a database analysis. Regional Anesthesia & Pain Medicine. 2019 Mar 1;44(3):303-8.

Cozowicz C, Poeran J, Zubizarreta N, Liu J, __Weinstein SM__, Pichler L, Mazumdar M, Memtsoudis SG. Non-opioid analgesic modes of pain management are associated with reduced postoperative complications and resource utilisation: a retrospective study of obstructive sleep apnoea patients undergoing elective joint arthroplasty. British Journal of Anaesthesia. 2019 Jan 1;122(1):131-40.

__Weinstein SM__, Poultsides L, Baaklini LR, Mörwald EE, Cozowicz C, Saleh JN, Arrington MB, Poeran J, Zubizarreta N, Memtsoudis SG. Postoperative delirium in total knee and hip arthroplasty patients: a study of perioperative modifiable risk factors. British journal of anaesthesia. 2018 May 1;120(5):999-1008.

__Weinstein SM__, YaDeau JT, Memtsoudis SG. Lack of association between levels and length of intraoperative controlled hypotension and acute kidney injury in total hip arthroplasty patients receiving neuraxial anesthesia. Regional Anesthesia & Pain Medicine. 2018 Oct 1;43(7):725-31.

__Weinstein SM__, Baaklini LR, Liu J, Poultsides L, Cozowicz C, Poeran J, Saleh JN, Memtsoudis SG. Neuraxial anaesthesia techniques and postoperative outcomes among joint arthroplasty patients: is spinal anaesthesia the best option?. British journal of anaesthesia. 2018 Oct 1;121(4):842-9.

#### __Select presentations__

__SM Weinstein__, KA Linn, RT Shinohara. _Two-stage stratified PCA for dimension reduction and nuisance variable mitigation_. Joint Statistical Meetings (August 2020, virtual due to COVID-19)

__SM Weinstein__, KA Linn, RT Shinohara. _Two-Stage PCA for Dimension Reduction & Mitigation of Nuisance Variable Associations_. Eastern North American Region of the International Biometric Society 2020 Spring Meeting (March 2020, virtual due to COVID-19)

__SM Weinstein__, LR Baaklini, J Liu, L Poultsides, C Cozowicz, J Poeran, SG Memtsoudis. _Does subtype of neuraxial anesthesia impact risk for adverse perioperative outcomes in hip and knee arthroplasty patients?_ 2018 World Congress on Regional Anesthesia & Pain Medicine (April 2018, New York, NY) 

__SM Weinstein__, C Cozowicz, EE Mörwald, L Pichler, LR Baaklini, L Poultsides, J Poeran, NE Sharrock, EM Soffin, SG Memtsoudis. _Delirium After Unilateral Total Hip and Knee Arthroplasty: A Retrospective Analysis of Modifiable Risk Factors._ American Society of Anesthesiologists Annual Meeting (Oct 2017, Boston, MA)

L Pichler, __SM Weinstein__, C Cozowicz, J Poeran, SG Memtsoudis. _The perioperative impact of sleep apnea in a high-volume specialty practice with focus on regional anesthesia._ Society for Anesthesia and Sleep Medicine Annual Meeting (Oct 2017, Boston, MA). Awarded 2nd Place Abstract Price.

__SM Weinstein__, EE Mörwald, C Cozowicz, LR Baaklini, L Poultsides, J Poeran, NE Sharrock, SG Memtsoudis. _Does type of anesthesia influence postoperative delirium in total knee arthroplasty patients?_ 42nd Annual Regional Anesthesia and Acute Pain Medicine Meeting (April 2017, San Francisco, CA)
